# Generated by Django 5.0.2 on 2024-05-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_cateogry_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cateogry",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.cateogry",
            ),
        ),
    ]
