# Generated by Django 5.0.2 on 2024-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_cateogry_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cateogry",
            options={
                "verbose_name": "Inventory Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterField(
            model_name="cateogry",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
